export const SCREEN = {
  CATEGORIES: 'CATEGORIES_SCREEN',
  CATEGORY_MEALS: 'CATEGORY_MEALS',
  MEAL_DETAIL: 'MEAL_DETAIL',
  FAVORITES: 'FAVORITES_SCREEN',
  TAB: 'TAB',
  FILTER: 'FILTER_SCREEN',
  DRAWER: 'DRAWER',
};
